import { getClient } from "@/apollo/client"
import Navbar from "@/components/Navbar/Navbar"
import { GET_NAVBAR_DATA } from "@/queries/get-navbar-data"
import './styles/global.scss'
import {config} from "@fortawesome/fontawesome-svg-core"
config.autoAddCss = false;

export const metadata = {
  title: 'Climate Change Hub',
  description: 'Generated by Next.js',
}



export default async function RootLayout({ children }) {
  const { data, error, loading } = await getClient().query({query: GET_NAVBAR_DATA})

  console.log("Data", data)

  return (
    <html lang="en">
      <body>
        <Navbar data={data} error={error} loading={loading} />
        {children}
        
        </body>
    </html>
  )
}
